#!/bin/sh
#SBATCH -p standard
#SBATCH --mem=4gb
#SBATCH -c 1
#SBATCH -a 0-30
#SBATCH -t 3-01:00:00  
#SBATCH -J tanv_trainer
#SBATCH -o /scratch/mtanveer/output/trainer_output%j
#SBATCH -e /scratch/mtanveer/output/trainer_error%j

module load anaconda
echo $SLURM_ARRAY_TASK_ID
# Running experiment 1
python -c "import os;import ted_talk_train as t;t.exp1_train_SSE(outdir='run_{}/'.format(os.environ['SLURM_ARRAY_TASK_ID']))"
#python -c "import os;import ted_talk_train as t;t.exp2_evaluate_SSE(outdir='run_{}/'.format(os.environ['SLURM_ARRAY_TASK_ID']))"
